// <auto-generated />
namespace CorkDistrict.Migrations.MigrationsModels
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Modeltest1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modeltest1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405170456493_Modeltest1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
